[tool.briefcase]
project_name = "PrintBoxCalc"
bundle = "com.skidoroot"
version = "1.2"
license.file = "LICENSE"
author = "5kidRo0t"
author_email = "skidoroot@gmail.com"
description = "Calculadora de clichés para maquinaria industrial HGL-924"

[tool.briefcase.app.printboxcalc]
formal_name = "PrintBoxCalc"
description = "Calculadora de clichés para maquinaria industrial HGL-924"
sources = ["src/printboxcalc"]
requires = [
    "toga-android==0.4.7"
]

icon = "icons/skull"
splash_background_color = "#FFFFFF"

[tool.briefcase.app.printboxcalc.android]
build_gradle_dependencies = [
    "androidx.appcompat:appcompat:1.0.2",
    "androidx.constraintlayout:constraintlayout:1.1.3",
    "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
]

